---
- name: Import 1Password GPG key
  ansible.builtin.rpm_key:
    key: https://downloads.1password.com/linux/keys/1password.asc
    state: present

- name: Add 1Password stable repo
  ansible.builtin.yum_repository:
    name: 1password
    description: 1Password Stable Channel
    baseurl: https://downloads.1password.com/linux/rpm/stable/$basearch
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: https://downloads.1password.com/linux/keys/1password.asc
    enabled: true

- name: Install 1Password desktop and CLI
  ansible.builtin.dnf:
    name:
      - 1password
      - 1password-cli
    state: present
