---
- name: Set up dotfiles
  hosts: localhost
  connection: local
  roles:
    - tmux
    - bbplayer

- name: Fedora system packages and tweaks
  hosts: localhost
  connection: local
  become: true
  roles:
    - role: fedora
      when: ansible_facts['distribution'] == "Fedora"
