monitor.bluez.rules = [
  {
    matches = [
      { node.name = "~bluez_output.*" }
      { node.name = "~bluez_input.*" }
    ] 
    actions = {
      update-props = {
        node.pause-on-idle = false
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
