# ~/.config/foot/foot.ini
[main]
font=IosevkaTerm Nerd Font:size=11
shell=/usr/bin/zsh
login-shell=yes

[csd]
preferred=client
border-width=1
border-color=7f000000

# Optional: make underline/cursor a bit clearer on light bg
# underline-thickness=2

[colors-light]
# Light theme base
background=ffffff
foreground=171421

[colors-dark]
background=ffffff
foreground=171421

# Normal 0-7
regular0=171421  # black
regular1=C01C28  # red
regular2=26A269  # green
regular3=A2734C  # yellow
regular4=12488B  # blue
regular5=A347BA  # magenta
regular6=2AA1B3  # cyan
regular7=D0CFCC  # white

# Bright 8-15
bright0=5E5C64   # bright black
bright1=F66151   # bright red
bright2=33D17A   # bright green
bright3=E9AD0C   # bright yellow
bright4=2A7BDE   # bright blue
bright5=C061CB   # bright magenta
bright6=33C7DE   # bright cyan
bright7=ffffff   # bright white

# [clipboard]
# Allow OSC 52 (remote apps can set/read clipboard via escape sequences)
# osc52=enabled

# [key-bindings]
# clipboard-copy=Control+c
# clipboard-paste=Control+v

# Keep the usual terminal-friendly ones too
# clipboard-copy=Control+Shift+c
# clipboard-paste=Control+Shift+v
